apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: myds
spec:
  selector:
    matchLabels:
      type: WebServer
  template:
    metadata:
      name: mypod
      labels:
        type: WebServer
    spec:
      containers:
        - name: c1
          image: nginx
