apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myrs

spec:
  replicas: 3
  selector:
    matchLabels:
      type: WebServer
  template:
    metadata:
      name: nginx-pod
      labels:
        type: WebServer
        env: QA
    spec:
      containers:
        - name: nginx-container
          image: nginx
