apiVersion: v1
kind: Service
metadata:
  name: mysvc
spec:
  type: NodePort
  ports:
    - targetPort: 80    # POD port
      port: 80          # Service port
      nodePort: 30001   # Node port
  selector:
    type: WebServer
